version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 8080:5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    networks:
      - backend
networks:
  backend:
